name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          git clone https://github.com/raysan5/raylib external/raylib
          mkdir -p external/raylib/build
          cd external/raylib/build
          cmake .. -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/external/raylib-install \
            -DCUSTOMIZE_BUILD=ON -DPLATFORM=Desktop -DGLFW_BUILD_WAYLAND=ON \
            -DGLFW_BUILD_X11=ON -DBUILD_SHARED_LIBS=OFF \
            -DX11_X11_INCLUDE_PATH=/usr/include -DX11_X11_LIB=/usr/lib/libX11.so
          cmake --build . --target install

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/external/raylib-install
          cmake --build .

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ttt
          path: ttt

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Binary
        uses: actions/download-artifact@v3
        with:
          name: ttt

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ttt
